### ISSUE TITLE
testing - what to do about .npy files?

### ISSUE THREAD

**Issue by ghost** [honeygupta/UW-Net#1]
hey, would it be possible for you to adjust the code so that I don't need `.npy` files for testing? Or could you explain how to obtain the `.npy` files (for testing)

**Comment by honeygupta** [comment]
Hi Aljo, 

A simple workaround would be to create a numpy array of zeros with dimensions 256x256x4 and save it as .npy file. You can use that to create the input lists. 

And I'm a bit preoccupied right now, but I'll try to fix the issue asap.

**Comment by ghost** [comment]
Okay, got it working. Thank you

**Comment by honeygupta** [comment]
Resolved this by adding a 'test.py' file and have added usage instructions to the README file.
