### ISSUE TITLE
Do you have the evaluation code for Berman dataset?

### ISSUE THREAD

**Issue by AttackonMuggle** [honeygupta/UW-Net#10]
Thank you for the pre-trained model and test code.
I'm a little confused about evaluating the Berman dateset. Could you please share the evaluation code for Berman you showed in Tab 1?

**Comment by honeygupta** [comment]
Hi, you can find the evaluation codes in this script - https://github.com/honeygupta/UW-Net/blob/master/evaluate_metrics.py

**Comment by AttackonMuggle** [comment]
Thanks for your reply, but how did you prepare the ground-truth images. Since in evaluate_metrics.py line 41, the gt between 0-255 will all be converted to 0.
