### ISSUE TITLE
How to convert .mat to GT images?

### ISSUE THREAD

**Issue by ZHAOQIII** [honeygupta/UW-Net#5]
Sorry to bother. I try to convert it with its evaluation code，but I don't know its max depth when I save it. Thanks.

**Comment by honeygupta** [comment]
Are you asking about the .mat files from Berman et al.'s dataset?

**Comment by ZHAOQIII** [comment]
Yes.

**Comment by honeygupta** [comment]
Sorry for the late reply. You can read them using scipy.io and normalize to get an image between 0-255 or 0-1.
