### ISSUE TITLE
Ask for codes

### ISSUE THREAD

**Issue by BIGWangYuDong** [honeygupta/UW-Net#6]
Hi,

I cannot find the code of your reference paper: 
![20200417214850](https://user-images.githubusercontent.com/48282753/79576050-43bca200-80f5-11ea-8e1f-9cce622a1f92.png)

paper 5, writen by Drews and 
paper 7, writen by peng.

**Comment by honeygupta** [comment]
Hi,

You can find the code for UDCP [5] here: https://www.researchgate.net/publication/309585520_UDCP_MATLAB_Code_of_the_paper_Underwater_Depth_Estimation_and_Image_Restoration_Based_on_Single_Images

For the method by Peng _et al._ [7], we got the code from the authors and hence can't provide it publicly. Kindly mail the authors for the same.

Regards
Honey

**Comment by BIGWangYuDong** [comment]
OK, I'll ask the authors. Thaks a lot!
Best regards,
Dong

**Comment by BIGWangYuDong** [comment]
Hello, one more question is that I found the result of UDCP [5] is different from your paper:
![20200418003850](https://user-images.githubusercontent.com/48282753/79592816-24ca0a00-810d-11ea-8032-10bc6684f892.png)
Do I need to change something that I can get the same result as yours?

Really thanks!
Donf

**Comment by honeygupta** [comment]
Is this the depth-map or the transmission-map?

**Comment by BIGWangYuDong** [comment]
The depth-map, but I didn't find how to traslate the transmission-map to depth-map. The code only can output trans-map?

**Comment by BIGWangYuDong** [comment]
![20200418005411](https://user-images.githubusercontent.com/48282753/79594232-3e6c5100-810f-11ea-8243-195420ee178d.png)


I can only get this code. Is this the true code?

**Comment by honeygupta** [comment]
Yes, it's the correct code and t2 is the transmission-map. You can obtain the depth-map by using this relation: t(x) =exp(−βd(x)). You can consider β as 1, as mentioned in the UDCP paper.

**Comment by BIGWangYuDong** [comment]
OK, I have just re-read your paper and find the answer, LOL, Thanks again!

**Comment by honeygupta** [comment]
Welcome!
