### ISSUE TITLE
SI-MSE calculation

### ISSUE THREAD

**Issue by reutazaria** [honeygupta/UW-Net#8]
Hi,
Does the SI-MSE refer actually to MSE or RMSE?

Thank you

**Comment by honeygupta** [comment]
Hi,

It is a scale-invariant mean-squared error. It was proposed by Eigen _et al._ in this paper: https://arxiv.org/pdf/1406.2283.pdf.
You can refer Equation 1 of this paper for the error definition.

The code for calculating the measure can be found [here](https://github.com/honeygupta/UW-Net/blob/b95324a6691d0a152873a7df85ec1e2f99110aca/evaluate_metrics.py#L8).

Honey
