### ISSUE TITLE
How to finetune pre-trained model on new datasets?

### ISSUE THREAD

**Issue by ln-nan** [honeygupta/UW-Net#9]
How to finetune pre-trained model on new datasets? I have some new underwater images, I want to ask how to use the new RGB images fine-tuning pre-trained model. Do I need to use RGBD data when training?
If possible, would you mind provide the D-Hazy data set  in the form of .npy files？

**Comment by honeygupta** [comment]
You can just load the pre-trained model and run the training loop for few epochs. The instructions to load the model can be found in the Readme - https://github.com/honeygupta/UW-Net#restoring-from-the-previous-checkpoint.
You do not need the depth images as the model learns to estimate depth through unsupervised learning. And we cannot provide the D-Hazy dataset as we don't have rights for it. Please check their website and download from their.
